pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./bundler
    volumes:
      - /tmp/cache:/cache

  build:
    image: ruby:2.2.3
    environment:
      - RAILS_ENV=test
    commands:
      - ls -al .
      - bundle install --path=./bundler
      - ls -al ./bundler/ruby/2.2.0/gems/
      - rails -v
      - rake --version

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./bundler
    volumes:
      - /tmp/cache:/cache