pipeline:
  build:
    image: python:2.7.14
    environment:
    commands:
      - ls -al /usr/share/zoneinfo/
      - cat /etc/timezone
      - cat /etc/localtime
      - date
      - ln -sf /usr/share/zoneinfo/Asia/Bangkok /etc/localtime
      - ln -sf /usr/share/zoneinfo/Asia/Bangkok /etc/timezone
      - cat /etc/timezone
      - cat /etc/localtime
      - date
      - pip install -r requirement.txt
  build2:
    image: bananacoding/ruby-nodejs:2.4.2
    environment:
    commands:
      - ls -al /usr/share/zoneinfo/
      - cat /etc/timezone
      - cat /etc/localtime
      - date
      - ln -sf /usr/share/zoneinfo/Asia/Bangkok /etc/localtime
      - ln -sf /usr/share/zoneinfo/Asia/Bangkok /etc/timezone
      - cat /etc/timezone
      - cat /etc/localtime
      - date

  publish:
    image: python:2.7.14
    commands:
      - pip install -r requirement.txt
    when:
      branch: master