pipeline:
  build:
    image: python:2.7.14
    environment:
    commands:
      - pip install -r requirement.txt
      - echo 'success'
    when:
      status:  [ failure, success ]
  publish:
    image: python:2.7.14
    commands:
      - pip install -r requirement.txt
    when:
      branch: master
label: 
  - linux/amd64
  