pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /tmp/bundler
    volumes:
      - /tmp/cache:/cache

  build:
    image: ruby:2.2.3
    environment:
      - RAILS_ENV=test
    commands:
      - ls -al .
      - bundle install --path=/tmp/bundler
      - ls -al .

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /tmp/bundler
    volumes:
      - /tmp/cache:/cache