pipeline:
  build:
    image: python:2.7.14
    environment:
    commands:
      - pip install -r requirement.txt

  publish:
    image: python:2.7.14
    commands:
      - pip install -r requirement.txt
    when:
      branch: master

label:
  - main=1