pipeline:
  # restores the cache from a local volume
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount: [ /drone/site-packages ]
    volumes: 
      - /tmp/cache:/cache

  build:
    image: python:2.7.14
    environment:
    commands:
      - pwd
      - echo 'django' >> requirement.txt         
      - pip install -r requirement.txt
      - echo 'success'
    when:
      status:  [ failure, success ]

  # rebuild the cache in case new dependencies were
  # downloaded during your build
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount: [ /drone/site-packages ]
    volumes: 
      - /tmp/cache:/cache