pipeline:
  build:
    image: python:2.7.14
    environment:
      - TZ=Asia/Bangkok
    commands:      
      - cat /etc/timezone
      - cat /etc/localtime
      - date
      - pip install -r requirement.txt    
  publish:
    image: python:2.7.14
    commands:
      - pip install -r requirement.txt
    when:
      branch: master