pipeline:
  build:
    image: node
    environment:
    commands:
      - cp -a /drone/node_modules /root
      - rm -rf /drone/node_modules
      - npm -g install
      - npm run build
      - npm run tests
      - cp -a /root/node_modules /drone
    when:
      status:  [ failure, success ]

  cache:
    mount:
      - /drone/node_modules
      - /drone/site-packages
  