pipeline:
  build:
    image: python:2.7.14
    commands:
      - echo 'install requirement'
      - pip install -r requirement.txt
      - python -v
  publish:
    image: python:2.7.14
    commands:
      - pip install -r requirement.txt
    when:
      branch: master
labels:
  - main : false