pipeline:
  build:
    image: python:2.7.14
    environment:
    commands:
      - pip install -r requirement.txt
    drone-filter : "BIG_PROJECT"

  publish:
    image: python:2.7.14
    commands:
      - pip install -r requirement.txt
    when:
      branch: master
    drone-filter : "BIG_PROJECT"